language: go

go:
  - 1.5.2
  - release
  - tip

sudo: required

before_script:
  - git clone --depth 1 https://github.com/chriso/intern.git &&
    cd intern &&
    cmake . &&
    make &&
    sudo make install

script: go test -v ./...
