language: go

go:
  - 1.5.2
  - release
  - tip

before_script:
  - git clone --depth 1 https://github.com/chriso/intern.git &&
    cd intern &&
    cmake . &&
    make install

script: go test -v ./...
